model_list:
  - model_name: gpt-4.1-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY
  
  - model_name: phi-4-14b
    litellm_params:
      model: lm_studio/phi-4-abliterated
      api_key: os.environ/LM_STUDIO_API_KEY

  - model_name: gemma-3-4b
    litellm_params:
      model: lm_studio/mlabonne_gemma-3-4b-it-abliterated
      api_key: os.environ/LM_STUDIO_API_KEY

general_settings:
  master_key: os.environ/MASTER_KEY

litellm_settings:
