model_list:
  - model_name: gpt-4.1-mini
    model_info:
      input_cost_per_token: 0.4
      output_cost_per_token: 1.6
    litellm_params:
      model: gpt-4o-mini
      api_key: os.environ/CHATGPT_API_KEY
  
  - model_name: phi-4-14b
    model_info:
      input_cost_per_token: 0
      output_cost_per_token: 0
    litellm_params:
      model: lm_studio/phi-4-abliterated
      api_key: os.environ/LMSTUDIO_API_KEY

  - model_name: gemma-3-4b
    model_info:
      input_cost_per_token: 0
      output_cost_per_token: 0
    litellm_params:
      model: lm_studio/mlabonne_gemma-3-4b-it-abliterated
      api_key: os.environ/LMSTUDIO_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  request_timeout: 100
