services:
  litellm:
    container_name: litellm
    image: ghcr.io/berriai/litellm:main-latest
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - ./config.yaml:/app/config.yaml
    command: [ "--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8" ]
    environment:
      - DATABASE_URL=postgresql://llmproxy:${LITELLM_POSTGRES_PASSWORD}@litellm_db:5432/litellm
      - STORE_MODEL_IN_DB=True
    depends_on:
      - litellm_db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health/liveliness || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 40s

  litellm_db:
    image: postgres:alpine
    container_name: litellm_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=litellm
      - POSTGRES_USER=llmproxy
      - POSTGRES_PASSWORD=${LITELLM_POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d litellm -U llmproxy"]
      interval: 10s
      timeout: 5s
      retries: 5

  openwebui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 3000:8080
    volumes:
      - owui_data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - OPENAI_API_BASE_URL=http://host.docker.internal:4000/v1
      - DEFAULT_MODELS=gpt-4.1-mini
      - ENABLE_OLLAMA_API=False
      - ENABLE_IMAGE_GENERATION=True
      - IMAGE_GENERATION_ENGINE=automatic1111
      - IMAGE_SIZE=1024x768
      - IMAGE_STEPS=5
      - IMAGE_GENERATION_MODEL=Juggernaut-XI-Lightning.safetensors [7782222e93]
      - AUTOMATIC1111_BASE_URL=http://host.docker.internal:7860
      - AUTOMATIC1111_CFG_SCALE=1.5
      - AUTOMATIC1111_SAMPLER=DPM++ SDE
      - AUTOMATIC1111_SCHEDULER=Karras
    restart: unless-stopped
      
volumes:
  postgres_data:
    name: litellm_postgres_data
  owui_data:
